### ISSUE TITLE
Can not discover the services from mobile

### ISSUE THREAD

**Issue by PaulB2Code** [01org/webbluetooth-edison-demo#9]
Hi @kenchris ,

We tried to test the server programm but we get issues to enable communication between the device and the mobile or the computer.

Basically I clone the project and launch npm install. 

Then I start node main.js.

The programm seems working with url Beacon working and connexion with nrFConnect on the device without services.

root@edison:~/webbluetooth-edison-demo/server# node main.js
1485429038866 Device(s) Intel Edison
NFC feature disabled.
1485429039420 Connected Intel Edison
poweredOn
advertisingStart: success

Temperature change 4
Temperature change 6
Accepted Connection: 46:4c:de:9b:69:4a
Temperature change 5
Temperature change 6
Disconnected Connection: 46:4c:de:9b:69:4a
Accepted Connection: 9c:2a:70:65:08:de
Disconnected Connection: 9c:2a:70:65:08:de

But We can not communicate with the services to exchange data.

In nrFConnect the adress of the Bluetooth is 0xFEAA and not 0XFC00 as it should be. 

Do you know if there is a way to solve this issues. 

Thank you

**Comment by kenchris** [comment]
Are you attaching using the https://webbt-sensor-hub.appspot.com web site or are you running it locally?

Locally might not work since it requires https. Also, I have mostly used it with the Arduino lately, so it might be that a few things changed in the client, resulting in changes needed for the Edison server.

**Comment by kenchris** [comment]
Also, are you running default Edison firmware or the Ostro distro? I personally moved to Ostro as that is newer and fixed several issues. The code running on Intel Joule should be much closer to Ostro as well.

**Comment by PaulB2Code** [comment]
I try on the server and not locally. 

On my phone i do not connect but on my desktop i see the device but when i connect I get  the following error 

Requesting Bluetooth Device...
Connecting to GATT server...
Requesting primary service...
NotFoundError: No Services with specified UUID found in Device.


I am on an edison Arduino Breakout board with the following distribution: 
3.10.98-poky-edison+

I did not know Ostro. 
Could it solve my issues on edison board and not on joule? 

Thank you

**Comment by PaulB2Code** [comment]
And do Ostro still and will live ? Because it seems that since last year the github repo is going down. 

Do you have more news about that? As we want to implement our project on a long term.

Thank you

**Comment by kenchris** [comment]
It should work without Ostro as well, it used to at least.

- On ChromeOS at least you need to pair the device first
- On Windows, Web Bluetooth isn't there yet as Win10 doesn't expose GATT etc yet and also required pairing
- I got it working on Linux, ChromeOS and Android

**Comment by PaulB2Code** [comment]
I tried on Nexus 5 and on Linux with Chrome Os an two different edison board and I get the same error: 
NotFoundError: No Services with specified UUID found in Device.

And it works with other devices such a the playbulb. 

I will install Ostro and try if it is still an edison bord issues.

**Comment by kenchris** [comment]
Try running something like https://googlechrome.github.io/samples/web-bluetooth/device-info.html and later https://googlechrome.github.io/samples/web-bluetooth/get-characteristics.html

to see if you can get access to it. The code uses fc00 (and fc0a and fc0b for the characteristics).

If you enabled Android nearby, so you see the physical web beacon?

You might try fetching 'bleno' separately. It is currently using bleno from eddystone-beacon, as otherwise it would be using two versions of bleno which resulted in a conflict

**Comment by PaulB2Code** [comment]
On the link you send me :
I can not connect with fc00 value but with 0xfeaa or Edison (even if I did not change your code). 

When I change the number of fc00 with any other code, nothing changed. I can connect only with the system with the adress 0xfeaa.

I saw the Android nearby with no issue all the time even if I change de value. 

As presented in out presentation I keep your requirement
var bleno = require('eddystone-beacon/node_modules/bleno');
to avoid bleno issue. 

Tomorrow, I will try with Ostro.

**Comment by kenchris** [comment]
I now remember that bleno and bluez don't mix well, so you need to do something to turn off bluez daemon. That might be it. I think the bleno github has the info, or maybe I have in the README.ostro file

**Comment by PaulB2Code** [comment]
In fact, I kill bluez and it works now. (On poky)

systemctl disable bluetooth

But I will try Ostro as soon as I arrived to logging on it. 

Thank you again!!

**Comment by PaulB2Code** [comment]
I also found that if I use

beacon.advertiseUrl("https://goo.gl/9FomQC", {name: DEVICE_NAME});
 
Then my device UUID will be 0xfeaa no matter what UUID I give to the device 

bleno.startAdvertising(DEVICE_NAME, ['fc0f']);
